simplesocial/accounts/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
    url(r'login/$',auth_views.LoginView.as_view(template_name = 'accounts/login.html'),name='login'),
    url(r'logout/$',auth_views.LogoutView.as_view(),name='logout'),
    url(r'signup/$',views.SignUp.as_view(), name='signup')
]

simplesocial/groups/urls.py
#Groups URLS.PY

from django.conf.urls import url
from . import views

app_name = 'groups'

urlpatterns = [
    url(r'^$',views.ListGroups.as_view(), name='all'),
    url(r'^new/$',views.CreateGroup.as_view(),name='create'),
    url(r'posts/in/(?P<slug>[-\w]+)/$',views.SingleGroup.as_view(),name='single')
]

simplesocial/posts/urls.py
from django.conf.urls import url

from . import views

app_name = 'posts'

urlpatterns = [
    url(r'^$', views.PostList.as_view(), name='all'),
    url(r'new/$', views.CreatePost.as_view(), name='create'),
    url(r'by/(?P<username>[-\w]+)', views.UserPosts.as_view(), name='for_user'),
    url(r'by/(?P<username>[-\w]+)/(?P<pk>\d+)/$',views.PostDetail.as_view(), name='single'),
    url(r'delete/(?P<pk>\d+)/$',views.DeletePost.as_view(), name='delete'),
]

simplesocial/simplesocial/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$',views.HomePage.as_view(), name='home'),
    url(r'^accounts/',include('accounts.urls',namespace='accounts')),
    url(r'^accounts/',include('django.contrib.auth.urls')),
    url(r'^test/$', views.TestPage.as_view(), name='test'),
    url(r'^thanks/$', views.ThanksPage.as_view(), name='thanks'),
]

simplesocial/accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib import auth

# Create your models here.

class User(auth.models.User, auth.models.PermissionsMixin):

    def __str__(self):
        return "@{}.".format(self.username)

simplesocial/groups/models.py
from django.db import models
from django.utils.text import slugify
from django.core.urlresolvers import reverse
# Create your models here.
import misaka

from django.contrib.auth import get_user_model
from django import template

User = get_user_model()
register = template.Library()


class Group(models.model):
    name = models.CharField(max_length=225, unique=True)
    slug = models.SlugField(allow_unicode=True, unique=True)
    description = models.TextField(blank=True, default='')
    description_html = models.TextField(editable=False, default='', blank=True)
    members = models.ManyToManyField(User, through='GroupMember')

    def __str__(self):
        return self.name

    def save(self,*args,**kwargs):
        self.slug = slugify(self.name)
        self.description_html = misaka.html(self.description)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('groups:single', kwargs={'slug':self.slug})


class GroupMember(models.model):

    group = models.ForeignKey(Group,related_name='memberships')
    user = models.ForeignKey(User, related_name='user_groups')

    def __str__(self):
        return self.user.username

    class Meta:
        unique_together = ('group', 'user')

simplesocial/posts/models.py
from django.db import models
from django.core.urlresolvers import reverse
from django.conf import settings
import misaka

from groups.models import Group

from django.contrib.auth import get_user_model
# Create your models here.

User = get_user_model()

class Post(models.model):
    user = models.ForeignKey(User,related_name='posts')
    created_at = models.DateTimeField(auto_now=True)
    message = models.TextField()
    message_html = models.TextField(editable=False)
    group = models.ForeignKey(Group,related_name='posts', null=True, blank=True)

    def __str__(self):
        return self.message

    def save(self,*args, **kwargs):
        self.message_html = misaka.html(self.message)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('posts:single', kwargs={'username': self.user.username, 'pk':self.pk})

    class Meta:
        ordering = ['-created_at']
        unique_together = ['user', 'message']

simplesocial/accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

class UserCreateForm(UserCreationForm):

    class Meta:
        fields = ('username','email', 'password1', 'password2')
        model = get_user_model()

    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)
        self.fields['username'].label = 'Display Name'
        self.fields['email'].label = "Email Address"

simplesocial/accounts/views.py
from django.shortcuts import render
from django.core.urlresolvers import reverse_lazy
from . import forms
from django.views.generic import CreateView
# Create your views here.

class SignUp(CreateView):
    form_class = forms.UserCreateForm
    success_url = reverse_lazy('login')
    template_name = 'accounts/signup.html'

simplesocial/groups/views.py
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.core.urlresolvers import reverse
from django.views import generic
from .models import Group,GroupMember
# Create your views here.

class CreateGroup(LoginRequiredMixin,generic.CreateView):
    fields = ('name', 'description')
    model = Group

class SingleGroup(generic.DetailView):
    model = Group

class ListGroups(generic.ListView):
    model = Group

simplesocial/posts/views.py
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.urlresolvers import reverse_lazy

from django.http import Http404
from django.views import generic

from braces.views import SelectRelatedMixin
from . import models
from . import forms

from django.contrib.auth import get_user_model
User = get_user_model()

# Create your views here.

class PostList(SelectRelatedMixin, generic.ListView):
    model = models.Post
    select_related = ('user','group')


class UserPosts(generic.ListView):
    model = models.Post
    template_name = 'post/user_post_list.html'

    def get_queryset(self):
        try:
            self.post.user = User.objects.prefetch_related('posts').get(username__iexact=self.kwargs.get('username'))
        except User.DoesNotExist:
            raise Http404
        else:
            return self.post_user.posts.all()


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['post_user'] = self.post_user
        return context


class PostDetail(SelectRelatedMixin, generic.DetailView):
    model = models.Post
    select_related = ('user', 'group')

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(user__username__iexact=self.kwargs.get('username'))


class CreatePost(LoginRequiredMixin, SelectRelatedMixin, generic.CreateView):
    fields = ('message', 'group')
    model = models.Post

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.save()
        return super().form_valid(form)


class DeletePost(LoginRequiredMixin, SelectRelatedMixin, generic.DeleteView):
    model = models.Post
    select_related = ('user', 'group')
    success_url = reverse_lazy('posts:all')

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(user_id=self.request.user.id)

    def delete(self, request, *args, **kwargs):
        messages.success(self.request,'Post Deleted')
        return super().delete(*args,**kwargs)

simplesocial/simplesocial/views.py
from django.views.generic import TemplateView

class HomePage(TemplateView):
    template_name = 'index.html'

class TestPage(TemplateView):
    template_name = 'test.html'

class ThanksPage(TemplateView):
    template_name = 'thanks.html'

simplesocial/accounts/templates/accounts/login.html
{% extends "base.html" %}
{% load bootstrap3 %}

{% block content %}
<div class="container">
    <h1>Login</h1>
    <form method="POST">

        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" class="btn btn-default" value="Login">

    </form>
</div>
{% endblock %}

simplesocial/accounts/templates/accounts/signup.html
{% extends "base.html" %}
{% load bootstrap3 %}

{% block content %}
<div class="container">
    <h1>Sign Up</h1>
    <form method="POST">

        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" class="btn btn-default" value="Sign Up">

    </form>
</div>
{% endblock %}

simplesocial/groups/templates/groups/group_base.html
{% extends "base.html" %}

{% block content %}

<div class="container">
    <div class="row">
        {% block pregroup %}{% endblock %}

        {% block group_content %}{% endblock %}

        {% block postgroup %}{% endblock %}

    </div>
</div>

{% endblock %}

simplesocial/groups/templates/groups/group_detail.html
{% extends "group/groups_base.html" %}
{% block pregroup %}
<h1>{{group.name}}</h1>
<h2>Member Count: {{group.members.count}}</h2>

<div class="content">
    {% if user in group.members.all %}

    <a href="{% url 'groups:leave' slug=group.slug %}" class="btn-lg btn-fill btn-warning"><span class="glyphicon glyphicon-remove-circle"></span>Leave group</a>

    {% else %}

    <a href="{% url 'groups:join' slug=group.slug %}" class="btn-lg btn-fill btn-default"><span class="glyphicon glyphicon-ok-circle"></span>Join group</a>

    {% endif %}
</div>
{% endblock %}

{% block group_content%}
<div class="col-md-8">
    {% if group.posts.count ==0 %}

    <h2>No posts in this group!</h2>

    {% else %}
    {% for post in groups.posts.all %}
    {% include "posts/_post.html" %}

    {% endif %}
</div>

{% endblock %}

simplesocial/groups/templates/groups/group_form.html
{% extends "groups/group_base.html" %}
{% load bootstrap3 %}

{% block group_content %}
<h4>Create a new Group!</h4>

<form class="" action="{% url 'groups:create' %}" method="post" id="groupForm">
    {% csrf_token %}
    {% bootstrap_form form%}
    <input type="submit" class="btn btn-primary btn-large" value="Create">
</form>
{% endblock %}

simplesocial/groups/templates/groups/group_list.html
{% extends "groups/groups_base.html" %}

{% block pregroup %}
<div class="col-md-4">
    <div class="content">
        {% if user.is_authenticated %}

        <h2>Welcome Back!
        <a href="{% url 'posts:for_user' username=user.username%}">@{{user.username}}</a>
        </h2>

        {% endif %}
        <h2>Groups</h2>
        <p>Welcome to the groups page!</p>
    </div>
    {% if user.is_authenticated %}
    <a href="{% url 'groups:create' %}" class="btn btn-md btn-fill btn-warning">
        <span class="glyphicon glyphicon-plus=-sign">Create New Group!</span>
    </a>
    {% endif %}
</div>
{% endblock %}

{% block group_content %}
<div class="col-md-8">
    <div class="list-group">
        {% for group in object_list %}
        <a class="list-group-item" href="{% url 'groups:single' slug=groups.slug %}">
            <h3 class="title list-group-item-heading">{{group.name}}</h3>
            <div class="list-group-item-text container-fluid">
                {{group.description_html|safe}}
                <div class="row">
                    <div class="col-md-4">
                        <span class="badge">{{group.members.count}}</span>
                        member{{group.members.count|pluralize}}
                    </div>
                    <div class="col-md-4">
                        <span class="badge">{{groups.posts.count}}</span>
                        post{{group.post.count|pluralize}}
                    </div>
                </div>
            </div>
        </a>
        {% endfor %}
    </div>
</div>

{% endblock %}

simplesocial/posts/templates/posts/_post.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

simplesocial/posts/templates/posts/post_base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

simplesocial/posts/templates/posts/post_confirm_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

simplesocial/posts/templates/posts/post_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

simplesocial/posts/templates/posts/post_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

simplesocial/posts/templates/posts/post_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

simplesocial/posts/templates/posts/user_post_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

simplesocial/templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Star Social</title>

    <!-- Latest compiled and minified CSS -->

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>


    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'simplesocial/css/master.css'%}">


</head>
  <body>

    <nav class="navbar  mynav" role="navigation" id="navbar">
    			<div class="container">

            <a class="navbar-brand mynav" href="{% url 'home' %}">Star Social</a>

    					<ul class="nav navbar-nav navbar-right">
    						{% if user.is_authenticated %}
                      <li><a href="#" class="btn btn-simple">Post</a></li>
                      <li><a href="#" class="btn btn-simple">Groups</a></li>
                      <li><a href="#" class="btn btn-simple">Create Group</a></li>
                      <li><a href="{% url 'accounts:logout' %}" class="btn btn-simple">Log out</a></li>
    						{% else %}
                                  <li><a href="#"class="btn btn-simple">Groups</a></li>
    						      <li><a href="{% url 'accounts:login' %}" class="btn btn-simple">Log in</a></li>
    						      <li><a href="{% url 'accounts:signup' %}" class="btn btn-simple">Sign up</a></li>
    						{% endif %}
    					</ul>



    			</div>
    		</nav>
        <div class="container mycontent">
          {% block content %}

          {% endblock %}

        </div>



<canvas id="canvas"></canvas>



  </body>
  <script src="{% static "simplesocial/js/master.js"%}" type="text/javascript" ></script>

</html>

simplesocial/templates/index.html
<!DOCTYPE html>
{% extends "base.html" %}

{% block content %}

<h1>Welcome to Star Social!</h1>

{% endblock %}

simplesocial/templates/test.html
{% extends "base.html" %}

{% block content %}

<h1>You are Logged in!</h1>

{% endblock %}

simplesocial/templates/thanks.html
{% extends "base.html" %}
{% block content %}

<h1>Thanks for visiting, come back soon</h1>

{% endblock %}